### ISSUE TITLE
Provide a code format profile

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/krazo#105]
We should define a standard code profile for Krazo. There is a default for EE4J projects. Maybe we should simply apply this one?

**Comment by erdlet** [comment]
Think that would be the easiest way and makes the most sense.

Christian Kaltepoth <notifications@github.com> schrieb am So., 20. Okt.
2019, 13:52:

**Comment by gtudan** [comment]
Let's go for the EE4J profile. These discussions tend to get lengthy and emotional. If we have a profile that no-one strongly opposes then let's go for it ;-)

**Comment by chkal** [comment]
I agree. So lets go with the EE4J profile. So maybe we just need a wiki page providing the corresponding links? What do you think?

**Comment by Daniel-Dos** [comment]
I believe that using EE4j is ideal since it will later be released by it.
--

*Daniel Dias dos Santos*
Java Developer
SouJava & JCP Member
GitHub: https://github.com/Daniel-Dos
Linkedin: www.linkedin.com/in/danieldiasjava
Twitter: http://twitter.com/danieldiasjava


Em seg, 21 de out de 2019 às 12:14, Christian Kaltepoth <
notifications@github.com> escreveu:

**Comment by gtudan** [comment]
> So maybe we just need a wiki page providing the corresponding links? What do you think?

We already have a `Contributing`-File. I think that would be a good place for the links.
