### ISSUE TITLE
OpenLiberty: CXF should call Krazo initialization on startup

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#157]
While debugging #147 we recognized, that it seems that the Krazo `CoreFeature` is not loaded when configurations are applied in JAX-RS `Application#getClasses`. This problem exists also with Jersey and RESTEasy where it is solved by some custom initalizers like [KrazoJerseyFeature](https://github.com/eclipse-ee4j/krazo/blob/236b5bbed18a43beed1b71ce76ecc1c183608ef4/jersey/src/main/java/org/eclipse/krazo/jersey/bootstrap/KrazoJerseyFeature.java#L40).

**Comment by chkal** [comment]
Just a quick summary of what I think the root cause is:

Krazo uses JAX-RS providers to implement the core functionality and the initialization procedure. This works fine in most cases by annotating classes with `@Provider`. However, if the user implements `Application.getClasses()`, JAX-RS will disable the automatic discovery of providers and Krazo will therefore not initialize correctly.

Jersey and RESTEasy have workaround for this (see [this comment](https://github.com/eclipse-ee4j/krazo/issues/147#issuecomment-584494354)). Maybe we find some way to fix this in CXF as well. If not, the user will have to manually include one or more Krazo related classes in `Application.getClasses()` which may be acceptable if we document it correctly.

**Comment by erdlet** [comment]
I just asked at the CXF mailinglist if there is some kind of interface like Jersey's `ForceAutoDiscovery` or any other mechanism we can use.

**Comment by erdlet** [comment]
Just recognized that there is an issue in the CXF Jira, which asks exactly for an interface like Jersey and RESTEasy are providing.

https://issues.apache.org/jira/browse/CXF-7611

**Comment by chkal** [comment]
Please note that JAX-RS 3.1 (which will most likely be released shortly after Jakarta EE 9, will fix this problem on the spec level:

https://github.com/eclipse-ee4j/jaxrs-api/blob/be10a259518b25bfd4dddaaaf680d425f944722c/jaxrs-api/src/main/java/jakarta/ws/rs/ext/Extension.java

**Comment by erdlet** [comment]
> So it MAY be ok to just document that using Application.getClasses() will force you to also register the corresponding Krazo providers.

I think that is OK for the moment, as there seems no way to fix this in CXF without the upcoming JAX-RS improvement. I'm afraid that CXF will need some time to implement JAX-RS 3.1, but I guess this will happen before implementing the mentioned JIRA issue.

**Comment by erdlet** [comment]
Until the JAX-RS enhancement for forced extension loading is released, the [documentation](https://github.com/eclipse-ee4j/krazo/blob/master/documentation/src/main/asciidoc/_quickstart.adoc) needs to be enough, as no other way is working on CXF.

I'll mark the issue as "waiting for dependency" or something similar, so we know, that there is nothing to do for the moment.

**Comment by chkal** [comment]
I'm wondering whether it also makes sense to use labels for marking issues as being related to a specific JAX-RS implementation. Something like `compat:cxf`!?

**Comment by erdlet** [comment]
Yes, we can do this also. At the moment, I write this information in the issue topic, but a label might be better.

**Comment by erdlet** [comment]
Because of OpenLibertys switch to RESTEasy in their next major release, we'll drop the CXF support in Krazo. So this issue is obsolete.
