### ISSUE TITLE
Error on mising view file not logged

### ISSUE THREAD

**Issue by thomas-mc-work** [eclipse-ee4j/krazo#202]
Selecting a nonexistent view file in a controller method returns a `HTTP Status 500 - Internal Server Error` response to the browser as expected. But this is a generic message without any details of the cause of that error. Also, a log entry like this would be very helpful:

    Referenced view file not found: "missing.jsp"

I'd try to fix it myself if you point me to the right place in the code.

**Comment by chkal** [comment]
Thanks for reporting this. Unfortunately fixing it could be difficult, because Krazo actually doesn't read or evaluate the JSP itself but simply forwards the request to the JSP engine without knowing if the specific view existing or not. 

All the magic is happening here:

https://github.com/eclipse-ee4j/krazo/blob/91f72411c35daaea555219e4f9667e68a978a75b/core/src/main/java/org/eclipse/krazo/engine/ServletViewEngine.java#L65-L121

We COULD try to catch exceptions thrown by `RequestDispatcher#forward` and add more details to the `ViewEngineException` thrown here:

https://github.com/eclipse-ee4j/krazo/blob/91f72411c35daaea555219e4f9667e68a978a75b/core/src/main/java/org/eclipse/krazo/engine/JspViewEngine.java#L60

**Comment by thomas-mc-work** [comment]
Phew, much more tricky than I expected :eyes:

**Comment by chkal** [comment]
Yeah, unfortunately it is. Not sure TBH what exception is thrown by `RequestDispatcher.forward()` in this case.
