### ISSUE TITLE
Remove velocity-tools from the Velocity-Extension

### ISSUE THREAD

**Issue by gtudan** [eclipse-ee4j/krazo#96]
The Velocity-Extension uses the velocity-tools. They have quiet a lot of other dependencies in addition to the Velocity-Engine that we don‘t really need. Those dependencies increase the attack surface of our users applications if they contain security issues (as happened in #92). 
The Velocity Tools are also quiet a bit behind the current version of the velocity engine and aren‘t updated as often.

Since we only use a single class (the Resource Loader) we should try to use the Velocity Engine directly and drop the dependency to the tools. Our users should still be free to use the tools (overriding the engine version) if they need them.

**Comment by chkal** [comment]
Big +1.

**Comment by erdlet** [comment]
Seems that it won't be that easy to remove this dependency. The resource loader we use is only available in this tools dependency and the documentation for web applications with Velocity refers to it. I tried other resource loaders but nothing worked.

The alternative, suggested by the documentation, would be to write a custom resource loader. But I'm sure the last thing we want is to maintain such a thing.

I'm not sure if I remember correct, but wasn't there in some issue a discussion about the extensions and if all of them should be continued (I think to remember, someone mentioned most of them were PoCs)? Maybe we should think about these extension and remove some of them, e.g. when they are based on really old stuff or (nearly) unmaintained frameworks.

**Comment by chkal** [comment]
Actually I would love to keep the Velocity extension, because Velocity was quite popular and gains more popularity now as the work on it seems to be continued.

I'm not super familiar with Velocity, but back then we had quite some issues because the Velocity Tools project didn't release new versions and got out of sync with the actual Velocity versions.

> The alternative, suggested by the documentation, would be to write a custom resource loader. But I'm sure the last thing we want is to maintain such a thing.

IMO the big question is whether this is really hard to do or not. I'm more familiar with Freemarker but implementing a resource loader of Freemarker is actually a no-brainer. And in this case I would be fine with maintaing our owner loader. Specially because AFAIK we already do it for other template engines.

Just my 2 cents.

**Comment by gtudan** [comment]
I guess we are talking about this class?
https://github.com/apache/velocity-tools/blob/trunk/velocity-tools-view/src/main/java/org/apache/velocity/tools/view/WebappResourceLoader.java <https://github.com/apache/velocity-tools/blob/trunk/velocity-tools-view/src/main/java/org/apache/velocity/tools/view/WebappResourceLoader.java>

It looks like the class has no other dependencies to anything else in the package. It’s under Apache license. Maybe I’m a bit to naive, but can’t we just take it (with the license header) and drop it into the package?

The class is pretty short (it contains a lot of comments and the bracket style is more verbose than ours) - if we would have to rewrite it, it should be doable in ~100 lines of code .While I don’t want to maintain to much code that isn’t directly related to Krazo either, I think that this isn’t to much of a  burden.

Too bad that this class isn’t in the core package of velocity. :-(

**Comment by erdlet** [comment]
Correct, I talked about this class.

> Maybe I’m a bit to naive, but can’t we just take it (with the license header) and drop it into the package?

Hmmm that could be an idea, but I've no big knowledge about this license stuff, so no idea if this could work.

> The class is pretty short (it contains a lot of comments and the bracket style is more verbose than ours) 

Yeah, maybe I was a bit confused about the class because of this bracket style. After having a look on it again, I agree with you, that isn't much code.


> Too bad that this class isn’t in the core package of velocity. :-(

:+1:

**Comment by chkal** [comment]
> It looks like the class has no other dependencies to anything else in the package. It’s under Apache license. Maybe I’m a bit to naive, but can’t we just take it (with the license header) and drop it into the package?

AFAIK this would be possible.

However, I already implemented ResourceLoaders for Velocity in the past and the process is actually straight forward. So rewriting it would also be an option. I guess I will find some time for this later today. Perhaps I'll simply create a first draft to see if the tests are still green with a simple version.

> Too bad that this class isn’t in the core package of velocity. :-(

My guess is that it is about the dependency on the Servlet API.

**Comment by chkal** [comment]
See #109 for a first draft.

**Comment by chkal** [comment]
Closed via #109
